backend:
  name: git-gateway
  branch: master
media_folder: 'public/images/uploads'
public_folder: '/images/uploads'
site_url: https://u-berlin.netlify.app/
display_url: https://u-berlin.netlify.app/
logo_url: https://u-berlin.netlify.app/images/logo.png
collections:
  - name: 'pages'
    label: 'Paginas'
    files:
      - name: 'home'
        label: 'Home'
        description: 'Aca puedes editar los elementos del Home.'
        file: content/index.md
        fields:
          - { label: 'Titulo', name: 'title', widget: 'string' }
          - { label: 'Slogan', name: 'slogan', widget: 'text' }
          - {
              label: 'Titulo Servicios',
              name: 'servicesTitle',
              widget: 'string',
            }
          - {
              label: 'Subtitulo Servicios',
              name: 'servicesSubtitle',
              widget: 'text',
            }
          - name: 'services'
            label: 'Servicios'
            widget: list
            fields:
              - { label: 'Titulo', name: 'title', widget: 'string' }
              - { label: 'Descripcion', name: 'description', widget: 'text' }
              - { label: 'Imagen', name: 'img', widget: 'string' }
          - { label: 'Titulo Tarifas', name: 'tariffsTitle', widget: 'string' }
          - name: 'tariffs'
            label: 'Tarifas'
            widget: list
            fields:
              - { label: 'Titulo', name: 'title', widget: 'string' }
              - { label: 'Descripcion', name: 'description', widget: 'text' }
              - { label: 'Precio', name: 'price', widget: 'string' }
              - { label: 'Unidad', name: 'unit', widget: 'string' }
      - name: 'contact'
        label: 'Contacto'
        description: 'Aca puedes editar los datos de contacto.'
        file: content/contact.md
        fields:
          - { label: 'Direccion', name: 'address', widget: 'text' }
          - { label: 'Telefono', name: 'phone', widget: 'text' }
          - { label: 'Email', name: 'email', widget: 'text' }
          - { label: 'Facebook', name: 'facebook', widget: 'text' }
          - { label: 'Linkedin', name: 'linkedin', widget: 'text' }
