backend:
  name: git-gateway
  branch: master
media_folder: public/images
public_folder: img
collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - label: 'Home'
        name: 'home'
        file: 'content/tarrifs.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Publish Date', name: 'date', widget: 'datetime' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
          - label: 'Tarifas'
            name: 'tariffs'
            widget: list
            fields:
              - { label: 'Titulo', name: 'title', widget: 'string' }
              - { label: 'Descripcion', name: 'description', widget: 'text' }
              - { label: 'Precio', name: 'price', widget: 'text' }
              - { label: 'Unidad', name: 'unit', widget: 'text' }
