backend:
  name: git-gateway
  branch: master
media_folder: 'public/images/uploads'
public_folder: '/images/uploads'
site_url: https://u-berlin.netlify.app/
display_url: https://u-berlin.netlify.app/
logo_url: https://u-berlin.netlify.app/images/logo.png
collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - name: 'index'
        label: 'Index'
        description: 'Aca puedes editar los elementos del index de la pagina.'
        file: content/index.md
        fields:
          - { label: 'Titulo', name: 'title', widget: 'string' }
          - { label: 'Subtitulo', name: 'subtitle', widget: 'text' }
          - name: 'tariffs'
            label: 'Tariffs'
            widget: list
            fields:
              - { label: 'Titulo', name: 'title', widget: 'string' }
              - { label: 'Descripcion', name: 'description', widget: 'text' }
              - { label: 'Precio', name: 'price', widget: 'string' }
              - { label: 'Unidad', name: 'unit', widget: 'string' }
