backend:
  name: test-repo
  branch: develop
media_folder: public/images
public_folder: out
collections:
  - name: 'tariffs'
    label: 'Tariffs'
    folder: content
    description: Agrega las Tarifas del index aca
    create: true
    fields:
      - { label: 'Descripcion', name: 'description', widget: 'text' }
      - { label: 'Titulo', name: 'title', widget: 'string' }
      - { label: 'Precio', name: 'price', widget: 'text' }
      - { label: 'Unidad', name: 'unit', widget: 'text' }
    # file: 'content/tarrifs.md'
    # files:
    # - label: 'Home'
    #   name: 'home'
    #   fields:
    #     - { label: 'Title', name: 'title', widget: 'string' }
    #     - { label: 'Publish Date', name: 'date', widget: 'datetime' }
    #     - { label: 'Body', name: 'body', widget: 'markdown' }
    # - label: 'Tarifas'
    #   name: 'tariffs'
    #   file: 'content/tarrifs.md'
    #   widget: list
    #
