backend:
  name: git-gateway
  branch: master
media_folder: 'public/images'
public_folder: '/images'
collections:
  - name: 'tariffs'
    label: 'Tariffs'
    folder: 'content/tariffs'
    widget: list
    description: Agrega las Tarifas del index aca
    create: true
    fields:
      - { label: 'Descripcion', name: 'description', widget: 'text' }
      - { label: 'Titulo', name: 'title', widget: 'string' }
      - { label: 'Precio', name: 'price', widget: 'text' }
      - { label: 'Unidad', name: 'unit', widget: 'text' }
